export const Data =[
    {
        id: 1,
        name: "Anas Raheem",
        desc: "Hello There, I am using WhatsApp",
        time: "8:21",
        messages: 5,
        img: "https://media.licdn.com/dms/image/v2/D4D03AQEflfDxWIQJuA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1713264864535?e=2147483647&v=beta&t=D88Lc9dIIHHIqT4CGH6Umlh7gEz9L6sdw-h3Jg4kRRY",
    },
    {
        id: 2,
        name: "Ahmed Ali",
        desc: "Let's catch up soon!",
        time: "9:30",
        messages: 2,
        img: "https://media.istockphoto.com/id/1347005975/photo/portrait-of-a-serious-muslim-young-man-looking-at-camera.jpg?s=612x612&w=0&k=20&c=mxRUDCuwDD3ML6-vMaUlTY7Ghqlj2R_LOhWWCB5CTXE=",
    },
    {
        id: 3,
        name: "Sara Khan",
        desc: "Meeting postponed to tomorrow",
        time: "10:45",
        messages: 7,
        img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    },
    {
        id: 4,
        name: "Hamza Malik",
        desc: "Call me when free",
        time: "12:00",
        messages: 3,
        img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
    },
    {
        id: 5,
        name: "Zara Sheikh",
        desc: "Can you send the files?",
        time: "1:15",
        messages: 4,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOGZpFZKQVdkcFBqhV0apckEr6CQk4s6bB_Q&s",
    },
    {
        id: 6,
        name: "Bilal Ahmed",
        desc: "Great job on the project!",
        time: "2:30",
        messages: 1,
        img: "https://img.freepik.com/free-photo/portrait-young-african-man-profile_176420-12620.jpg",
    },
    {
        id: 7,
        name: "Ayesha Noor",
        desc: "Thanks for the help!",
        time: "3:00",
        messages: 4,
        img: "https://www.shutterstock.com/image-photo/detailed-profile-shot-young-brunette-260nw-2503307217.jpg",
    },
    {
        id: 8,
        name: "Usman Tariq",
        desc: "See you at the event",
        time: "4:20",
        messages: 2,
        img: "https://img.freepik.com/free-photo/freedom-concept-with-hiker-mountain_23-2148107064.jpg",
    },
    {
        id: 9,
        name: "Fatima Zain",
        desc: "Happy Birthday!",
        time: "5:30",
        messages:7,
        img: "https://img.freepik.com/premium-photo/beautiful-young-girl-detail-head-with-female-human-ear-hair-close-up-portrait-profile_99433-112.jpg",
    },
    {
        id: 10,
        name: "Ali Raza",
        desc: "Let's go out for coffee",
        time: "6:45",
        messages: 6,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnD7Z0xW2eftTLFyUspr0kLJ8Fi_ynkdL5gA&s",
    },
    {
        id: 11,
        name: "Maria Javed",
        desc: "Don't forget the meeting",
        time: "7:50",
        messages: 1,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWS0xWCLhXuM9Y4UYjXtRDxRJ3QurnKCM6GQ&s",
    },
    {
        id: 12,
        name: "Kamran Shah",
        desc: "Thanks for sharing",
        time: "8:00",
        messages:4,
        img: "https://cdn.pixabay.com/photo/2023/04/21/15/42/portrait-7942151_640.jpg",
    },
    {
        id: 13,
        name: "Hassan Ali",
        desc: "What's the update?",
        time: "9:10",
        messages: 3,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7Jcee8NXlrNKSvJn_w463ncJK_cdsWe8Rt3qR5yX00imUsYGGiiFKZkqIK8ip7925L6k&usqp=CAU",
    },
    {
        id: 14,
        name: "Mehwish Sana",
        desc: "Long time no see!",
        time: "10:20",
        messages: 4,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkvj5el0ouTHNa_o__nt5Z003iMXnltsVofA&s",
    },
    {
        id: 15,
        name: "Saad Qureshi",
        desc: "Thanks, talk later",
        time: "11:45",
        messages: 2,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQln3CMvx6DX8ab9YXhmNbg7vfm7e2f9A44ZT_R3Aeu4852dU08Q3A2sA1LX6S6kiAWBx4&usqp=CAU",
    },
]